"""
app/papers/pdf_export.py — PDF generation using ReportLab
"""
import io
import uuid
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    HRFlowable,
    Table,
    TableStyle,
)
from reportlab.lib import colors
from reportlab.lib.colors import HexColor


def generate_pdf(paper: dict) -> bytes:
    """
    Generate a professional exam paper PDF from a paper dict.
    Returns raw PDF bytes.
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2.5 * cm,
        rightMargin=2.5 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = _build_styles()
    story = []

    # ── Header ───────────────────────────────────────────────────────────────
    story.append(Paragraph("BookToPaper", styles["institution"]))
    story.append(Paragraph(paper.get("title", "Question Paper"), styles["title"]))
    story.append(Spacer(1, 0.3 * cm))

    # Meta line: marks | duration | format
    meta = (
        f"Total Marks: {paper.get('total_marks', 100)}  |  "
        f"Duration: {paper.get('duration_mins', 180)} minutes  |  "
        f"Format: {paper.get('format', 'Custom').upper()}"
    )
    story.append(Paragraph(meta, styles["meta"]))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.black, spaceAfter=0.4 * cm))

    # General instructions
    general_instructions = paper.get("general_instructions")
    if general_instructions:
        story.append(Paragraph("General Instructions:", styles["section_header"]))
        story.append(Paragraph(general_instructions, styles["instruction"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey, spaceAfter=0.5 * cm))

    # ── Sections ─────────────────────────────────────────────────────────────
    for section in paper.get("sections", []):
        story.append(Paragraph(section.get("name", "Section"), styles["section_title"]))

        if section.get("rules") or section.get("instruction"):
            instr = section.get("rules") or section.get("instruction", "")
            story.append(Paragraph(instr, styles["instruction"]))

        story.append(Spacer(1, 0.3 * cm))

        for q in section.get("questions", []):
            q_num = q.get("number", q.get("id", "?"))
            q_text = q.get("text", q.get("question", ""))
            q_marks = q.get("marks", 0)

            # Build question row: [number + text] [marks]
            q_para = Paragraph(f"<b>{q_num}.</b>  {q_text}", styles["question"])
            marks_para = Paragraph(f"({q_marks} marks)", styles["marks"])

            table = Table(
                [[q_para, marks_para]],
                colWidths=["85%", "15%"],
            )
            table.setStyle(TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (1, 0), (1, 0), "RIGHT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(table)

            # MCQ options
            if q.get("options"):
                for i, opt in enumerate(q["options"]):
                    label = ["A", "B", "C", "D"][i] if i < 4 else str(i + 1)
                    story.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;({label}) {opt}", styles["option"]))
                story.append(Spacer(1, 0.2 * cm))

        story.append(Spacer(1, 0.5 * cm))

    # ── Footer line ───────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(
        f"Generated by BookToPaper · {datetime.now().strftime('%B %d, %Y')} · All rights reserved.",
        styles["footer"]
    ))

    doc.build(story)
    return buffer.getvalue()


def _build_styles() -> dict:
    base = getSampleStyleSheet()
    accent = HexColor("#CC785C")

    styles = {
        "institution": ParagraphStyle(
            "institution",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.grey,
            alignment=TA_CENTER,
            spaceAfter=4,
            fontName="Helvetica",
        ),
        "title": ParagraphStyle(
            "title",
            parent=base["Title"],
            fontSize=18,
            leading=22,
            textColor=colors.black,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
            spaceAfter=4,
        ),
        "meta": ParagraphStyle(
            "meta",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.grey,
            alignment=TA_CENTER,
            fontName="Helvetica",
            spaceAfter=6,
        ),
        "section_header": ParagraphStyle(
            "section_header",
            parent=base["Normal"],
            fontSize=10,
            fontName="Helvetica-Bold",
            spaceBefore=4,
            spaceAfter=2,
        ),
        "section_title": ParagraphStyle(
            "section_title",
            parent=base["Normal"],
            fontSize=12,
            fontName="Helvetica-Bold",
            textColor=accent,
            spaceBefore=12,
            spaceAfter=4,
            borderPad=4,
        ),
        "instruction": ParagraphStyle(
            "instruction",
            parent=base["Normal"],
            fontSize=9,
            fontName="Helvetica-Oblique",
            textColor=colors.darkgrey,
            spaceAfter=4,
            alignment=TA_JUSTIFY,
        ),
        "question": ParagraphStyle(
            "question",
            parent=base["Normal"],
            fontSize=11,
            leading=15,
            fontName="Helvetica",
            alignment=TA_JUSTIFY,
        ),
        "marks": ParagraphStyle(
            "marks",
            parent=base["Normal"],
            fontSize=9,
            fontName="Helvetica-Oblique",
            textColor=colors.darkgrey,
            alignment=TA_CENTER,
        ),
        "option": ParagraphStyle(
            "option",
            parent=base["Normal"],
            fontSize=10,
            fontName="Helvetica",
            spaceAfter=2,
            leftIndent=20,
        ),
        "footer": ParagraphStyle(
            "footer",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.grey,
            alignment=TA_CENTER,
            fontName="Helvetica",
        ),
    }
    return styles
